/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        sm: "100%",
        md: "100%",
        lg: "1024px",
        xl: "1280px",
      },
    },
    extend: {
      fontFamily: {
        sans: "var(--font-body)",
        deco: "var(--font-heading)",
      },
      fontSize: {
        canon: "var(--scale-canon)",
        trafalgar: "var(--scale-trafalgar)",
        paragon: "var(--scale-paragon)",
        "double-pica": "var(--scale-double-pica)",
        "great-primer": "var(--scale-great-primer)",
        "body-copy": "var(--scale-body-copy)",
        pica: "var(--scale-pica)",
        "long-primer": "var(--scale-long-primer)",
        brevier: "var(--scale-brevier)",
        minion: "var(--scale-minion)",
      },
      colors: {
        primary: "var(--color-primary)",
        "primary-50": "var(--color-primary-50)",
        "primary-100": "var(--color-primary-100)",
        "primary-200": "var(--color-primary-200)",
        "primary-300": "var(--color-primary-300)",
        "primary-400": "var(--color-primary-400)",
        "primary-500": "var(--color-primary-500)",
        "primary-600": "var(--color-primary-600)",
        "primary-700": "var(--color-primary-700)",
        "primary-800": "var(--color-primary-800)",
        "primary-900": "var(--color-primary-900)",
        secondary: "var(--color-secondary)",
        "secondary-50": "var(--color-secondary-50)",
        "secondary-100": "var(--color-secondary-100)",
        "secondary-200": "var(--color-secondary-200)",
        "secondary-300": "var(--color-secondary-300)",
        "secondary-400": "var(--color-secondary-400)",
        "secondary-500": "var(--color-secondary-500)",
        "secondary-600": "var(--color-secondary-600)",
        "secondary-700": "var(--color-secondary-700)",
        "secondary-800": "var(--color-secondary-800)",
        "secondary-900": "var(--color-secondary-900)",
        "dark-50": "var(--color-dark-50)",
        "dark-100": "var(--color-dark-100)",
        "dark-200": "var(--color-dark-200)",
        "dark-300": "var(--color-dark-300)",
        "dark-400": "var(--color-dark-400)",
        "dark-500": "var(--color-dark-500)",
        "dark-600": "var(--color-dark-600)",
        "dark-700": "var(--color-dark-700)",
        "dark-800": "var(--color-dark-800)",
        "dark-900": "var(--color-dark-900)",
        "light-50": "var(--color-light-50)",
        "light-100": "var(--color-light-100)",
        "light-200": "var(--color-light-200)",
        "light-300": "var(--color-light-300)",
        "light-400": "var(--color-light-400)",
        "light-500": "var(--color-light-500)",
        "light-600": "var(--color-light-600)",
        "light-700": "var(--color-light-700)",
        "light-800": "var(--color-light-800)",
        "light-900": "var(--color-light-900)",
      },
    },
  },
  plugins: [],
}
